"""add date and time to meetup

Revision ID: 12cb9432a2a4
Revises: 42996786066e
Create Date: 2023-07-18 13:02:39.554910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12cb9432a2a4'
down_revision = '42996786066e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('time', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetups', schema=None) as batch_op:
        batch_op.drop_column('time')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
