"""c/p from mai

Revision ID: 335011976776
Revises: 44fed9a4c9a3
Create Date: 2023-07-19 18:31:58.430368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335011976776'
down_revision = '44fed9a4c9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetup_attendees',
    sa.Column('meetup_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meetup_id'], ['meetups.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('meetup_id', 'pet_id')
    )
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')

    op.drop_table('meetup_attendees')
    # ### end Alembic commands ###
