"""empty message

Revision ID: 49167c600e14
Revises: ab4718bbc609
Create Date: 2023-07-17 19:23:50.328240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "49167c600e14"
down_revision = "ab4718bbc609"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meetups", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pet_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("venue", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("street_address", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("city", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("state", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("country", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("longtitude", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("latitude", sa.Float(), nullable=True))
        batch_op.create_foreign_key(
            "fk_meetups_pet_id_pets", "pets", ["pet_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meetups", schema=None) as batch_op:
        batch_op.drop_constraint("fk_meetups_pet_id_pets", type_="foreignkey")
        batch_op.drop_column("latitude")
        batch_op.drop_column("longtitude")
        batch_op.drop_column("country")
        batch_op.drop_column("state")
        batch_op.drop_column("city")
        batch_op.drop_column("street_address")
        batch_op.drop_column("venue")
        batch_op.drop_column("pet_id")

    # ### end Alembic commands ###
