"""add details to meetup

Revision ID: 5bcd07bdca69
Revises: e36c4cf91155
Create Date: 2023-07-18 18:45:35.689080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bcd07bdca69'
down_revision = 'e36c4cf91155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetups', schema=None) as batch_op:
        batch_op.drop_column('details')

    # ### end Alembic commands ###
