"""empty message

Revision ID: 9a43735db631
Revises: 12cb9432a2a4
Create Date: 2023-07-18 18:10:21.693966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a43735db631'
down_revision = '12cb9432a2a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetups', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('image')

    # ### end Alembic commands ###
