"""meetups table

Revision ID: af8dd6a6b50b
Revises: 49167c600e14
Create Date: 2023-07-18 10:49:40.247028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af8dd6a6b50b"
down_revision = "49167c600e14"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meetups", schema=None) as batch_op:
        if op.get_context().dialect.name == "sqlite":
            result = op.get_bind().execute(sa.text("PRAGMA table_info(meetups)"))
            columns = [row[1] for row in result.fetchall()]
            if "longitude" in columns:
                batch_op.drop_column("longitude")
        else:
            batch_op.drop_column("longitude")

    with op.batch_alter_table("pets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("owner_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("birth_year", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("species", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("breed", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("profile_pic", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("city", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("state", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("country", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("availability", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("longitude", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("latitude", sa.Float(), nullable=True))
        batch_op.create_foreign_key(
            "fk_pets_owner_id_users", "users", ["owner_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pets", schema=None) as batch_op:
        batch_op.drop_constraint("fk_pets_owner_id_users", type_="foreignkey")
        batch_op.drop_column("latitude")
        batch_op.drop_column("longitude")
        batch_op.drop_column("availability")
        batch_op.drop_column("country")
        batch_op.drop_column("state")
        batch_op.drop_column("city")
        batch_op.drop_column("profile_pic")
        batch_op.drop_column("breed")
        batch_op.drop_column("species")
        batch_op.drop_column("birth_year")
        batch_op.drop_column("name")
        batch_op.drop_column("owner_id")

    with op.batch_alter_table("meetups", schema=None) as batch_op:
        batch_op.add_column(sa.Column("longitude", sa.Float(), nullable=True))

    # ### end Alembic commands ###
